export const BookData = [
    {
        id: 0,
        book_name: "Upon This Mountain",
        book_description: "Mwambu will climb the mountain where he hopes to touch heaven, but his journey from naive curiosity to adulthood will reveal unexpected contradictions. His descent from the mountain - his maturation - lays bare the sexual, social, and religious conflicts he has to face. Timothy Wangusa's subtle wit and insight into the discoveries of childhood and adolescence make his first novel a compelling read.",
        book_url: "https://m.media-amazon.com/images/I/419VzKxawbL._SY425_.jpg",
        print_length: "128 pages",
        language: "English",
        author_name: "Timothy Wangusa",
        price: "25000",
    },
    {
        id: 1,
        book_name: "The Tale Of Kintu and Nambi",
        book_description: "The tale of kintu and nambi is an african (UGANDAN) traditional story about the first muganda and his cow. The tale goes about to show how Kintu and nambi met and the challenges they faced in creating the now great dynasty of Buganda.The legend is still popular to this day , as it contributes to the great heritage of the Baganda tribe in Uganda. Its a full picture book with interesting characters and strange happenings.",
        book_url: "https://m.media-amazon.com/images/I/71FSXY-WvQL._SL1294_.jpg",
        print_length: "30 pages",
        language: "English",
        author_name: "kasule RAPHEAL ALLAN",
        price: "15000",
    },
    {
        id: 2,
        book_name: "Devil On The Cross",
        book_description: "One of the cornerstones of Ngũgĩ wa Thiong’o’s fame, Devil on the Cross is a powerful fictional critique of capitalism. It tells the tragic story of Wariinga, a young woman who moves from a rural Kenyan town to the capital, Nairobi, only to be exploited by her boss and later by a corrupt businessman. As she struggles to survive, Wariinga begins to realize that her problems are only symptoms of a larger societal malaise and that much of the misfortune stems from the Western, capitalist influences on her country. An impassioned cry for a Kenya free of dictatorship and for African writers to work in their own local dialects, Devil on the Cross has had a profound influence on Africa and on post-colonial African literature.",
        book_url: "https://images4.penguinrandomhouse.com/cover/9780143107491?height=295&alt=cover_coming_soon.jpg",
        print_length: "256 pages",
        language: "English",
        author_name: "Ngugi wa Thiong'o",
        price: "20000",
    },
    {
        id: 3,
        book_name: "Betrayal In The City",
        book_description: "First published in 1976, this play from one of Africa's foremost dramatists is in the classic cannon. It is an incisive examination of the problems of independence and freedom in post-colonial Africa states, where few believe they have a stake in the future. In the words of one of the characters: 'It was better while we waited. Now we have nothing to look forward to. We have killed our past and are busy killing our future'. Francis Imbuga is a playwright and actor. He is the recipient of the Kenya National Academy of Sciences Distinguished Professional Award in Play Writing.",
        book_url: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1348027810i/3541753.jpg",
        print_length: "80 pages",
        language: "English",
        author_name: "Francis Imbuga",
        price: "15000",
    },
    {
        id: 4,
        book_name: "Voice Of The People",
        book_description: "OKIYA OMTATAH OKOITI is a well-known playwright. His first published work, Lwanda Magere (EAEP 1991), received enthusiastic response in Kenya and beyond. Owing to its rich literary lustre, it was made a set book for secondary schools in Tanzania. Besides writing plays, Okoiti is also a short story writer and media commentator on social, cultural, political and religious matters. In Voice of the People, Nasirumbi incurs the wrath and hostility of the powers-that-be for engaging in a crusade to save Simbi Forest. Led by Boss, the political leadership would stop at nothing to achieve its heinous goals. But it has to contend with the integrity and moral forthright-ness of Nasirumbi, whose unshakeable resolve ends up being a nightmare to Boss and his sycophants.",
        book_url: "https://textbookcentre.com/media/cache/de/f7/def7247e42e23aee31dfaa560bbc4757@2x.webp",
        print_length: "248 pages",
        language: "English",
        author_name: "Okiya Omtatah Okoiti",
        price: "30000",
    },
    {
        id: 5,
        book_name: "Things Fall Apart",
        book_description: "Things Fall Apart is the first of three novels in Chinua Achebe's critically acclaimed African Trilogy. It is a classic narrative about Africa's cataclysmic encounter with Europe as it establishes a colonial presence on the continent. Told through the fictional experiences of Okonkwo, a wealthy and fearless Igbo warrior of Umuofia in the late 1800s, Things Fall Apart explores one man's futile resistance to the devaluing of his Igbo traditions by British political andreligious forces and his despair as his community capitulates to the powerful new order.",
        book_url: "https://m.media-amazon.com/images/I/91NtvTU0xEL._SL1500_.jpg",
        print_length: "209 pages",
        language: "English",
        author_name: "Chinua Achebe",
        price: "28000",
    },
    {
        id: 6,
        book_name: "Left to tell: Discovering God Admist the Rwandan Holocaust",
        book_description: "Immaculee Ilibagiza grew up in a country she loved, surrounded by a family she cherished. But in 1994 her idyllic world was ripped apart as Rwanda descended into a bloody genocide. Immaculee’s family was brutally murdered during a killing spree that lasted three months and claimed the lives of nearly a million Rwandans.Incredibly, Immaculee survived the slaughter. For 91 days, she and seven other women huddled silently together in the cramped bathroom of a local pastor while hundreds of machete-wielding killers hunted for them. It was during those endless hours of unspeakable terror that Immaculee discovered the power of prayer, eventually shedding her fear of death and forging a profound and lasting relationship with God.She emerged from her bathroom hideout having discovered the meaning of truly unconditional love—a love so strong she was able seek out and forgive her family’s killers. The triumphant story of this remarkable young woman’s journey through the darkness of genocide will inspire anyone whose life has been touched by fear, suffering, and loss." ,
        book_url: "https://m.media-amazon.com/images/I/81aE0zRRU8L._SY425_.jpg",
        print_length: "256 pages",
        language: "English",
        author_name: "Immacuee Ilibagiza",
        price: "25000",
    },
    {
        id: 8,
        book_name: "Harry Potter and the Chamber of Secrets",
        book_description: "Harry Potter's summer has included the worst birthday ever, doomy warnings from a house-elf called Dobby, and rescue from the Dursleys by his friend Ron Weasley in a magical flying car! Back at Hogwarts School of Witchcraft and Wizardry for his second year, Harry hears strange whispers echo through empty corridors - and then the attacks start. Students are found as through turned to stone . Dobby's sinister predictions seem to be coming true.These new editions of the classic and internationally bestselling, multi-award-winning series feature instantly pick-up-able new jackets by Jonny Duddle, with huge child appeal, to bring Harry Potter to the next generation of readers. It's time to PASS THE MAGIC ON .",
        book_url: "https://m.media-amazon.com/images/I/51yzj3H34aL._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
        print_length: "224 pages",
        language: "English",
        author_name: "J.K. Rowling",
        price: "40000",
    },
    {
        id: 9,
        book_name: "The Promised Land",
        book_description:" Grace Ogot made history when she became the first African woman writer to have her English language works published in 1962 and 1964. Her first full-length novel, The Promised Land, was published in 1966, three years after Kenya gained its independence from British rule.In the story, she charts the journey of a young farmer and his wife after they migrate from Kenya to Tanzania. As they try to settle into their new home, the couple finds themselves embroiled in tribal conflict with their suspicious new neighbours. The disputes between them and the community grow in proportion to their prosperity, eventually boiling over into a devastating climax.",
        book_url: "https://www.booksafricana.com/wp-content/uploads/2021/01/The-Promised-Land.jpg",
        print_length: "384 pages",
        language: "English",
        author_name: "Grace Ogot",
        price: "26000",
    },
    {
        id: 10,
        book_name: "Paradise",
        book_description: "Paradise is at once the story of an African boy's coming of age, a tragic love story, and a tale of the corruption of traditional African patterns by European colonialism. It presents a major African voice to American readers - a voice that prompted Peter Tinniswood to write in the London Times, reviewing Gurnah's previous novel, 'Mr. Gurnah is a very fine writer. I am certain he will become a great one.' Paradise is Abdulrazak Gurnah's great novel. At twelve, Yusuf, the protagonist of this twentieth-century odyssey, is sold by his father in repayment of a debt. From the simple life of rural Africa, Yusuf is thrown into the complexities of precolonial urban East Africa - a fascinating world in which Muslim black Africans, Christian missionaries, and Indians from the subcontinent coexist in a fragile, subtle social hierarchy. Through the eyes of Yusuf, Gurnah depicts communities at war, trading safaris gone awry, and the universal trials of adolescence. Then, just as Yusuf begins to comprehend the choices required of him, he and everyone around him must adjust to the new reality of European colonialism. The result is a page-turning saga that covers the same territory as the novels of Isak Dinesen and William Boyd, but does so from a perspective never before available on that seldom-chronicled part of the world.",
        book_url: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1696305294i/765618.jpg",
        print_length: "256 pages",
        language: "English",
        author_name: "Abdulrazak Gurnah",
        price: "30000",
    },
    {
        id: 11,
        book_name: "The Alien Woman",
        book_description: "Two brothers - Opito and Obina from northern Uganda, are grappling with the strict creed of their culture. Opito is in love with beautiful, educated Gladys but his parents reject his choice. He is seized by a spirit in her form - the alien woman. Obina, is courted by a southern beauty who is at the same university. She is seen as an alien woman by Obina as well as his family and at first she is rejected. But she has qualities that transcend generations and cultures.",
        book_url: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1347622923i/7225020.jpg",
        print_length: "145",
        language: "English",
        author_name: "Laury Lawrence Ocean",
        price: "16000",
    },
    {
        id: 12,
        book_name: "Footprints of the Outsider",
        book_description: "This is the story of the life of Abudu Olwit, and of Teboke, the village where he is born and raised. In Teboke, two Indians build a cotton ginnery, and recruit workers from Sudan and the Congo to operate the ginnery, employing a white boss to discipline the immigrants. The workers live amongst the locals but do not own the land, or speak their languages. Abudu's mother sleeps with the workers of the ginnery, and so Abudu is born. He leaves the village to study for degrees, work and marry. Things soon turn sour though. and he lands himself in prison. Upon release, he returns to the village and all its problems, resolving to engage in politics. But he discovers that politics in inseparable from violence.",
        book_url: "https://m.media-amazon.com/images/I/510st6ekRwL._SY425_.jpg",
        print_length: "172 pages",
        language: "English",
        author_name: "Julius Ocwintyo",
        price: "20000",
    },
    {
        id: 13,
        book_name: "Cockroaches",
        book_description: "Imagine being born into a world where everything about you--the shape of your nose, the look of your hair, the place of your birth--designates you as an undesirable, an inferior, a menace, no better than a cockroach, something to be driven away and ultimately exterminated. Imagine being thousands of miles away while your family and friends are brutally and methodically slaughtered. Imagine being entrusted by your parents with the mission of leaving everything you know and finding some way to survive, in the name of your family and your people.Scholastique Mukasonga's Cockroaches is the story of growing up a Tutsi in Hutu-dominated Rwanda--the story of a happy child, a loving family, all wiped out in the genocide of 1994. A vivid, bitterwsweet depiction of family life and bond in a time of immense hardship, it is also a story of incredible endurance, and the duty to remember that loss and those lost while somehow carrying on. Sweet, funny, wrenching, and deeply moving, Cockroaches is a window onto an unforgettable world of love, grief, and horror.",
        book_url: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1469411865i/28503823.jpg",
        print_length: "165 pages",
        language: "English",
        author_name: "Scholastique Mukasonga, Jordan Stump (translator)",
        price: "40000",
    },
    {
        id: 14,
        book_name: "Facing the Lion: Growing Up Maasai on the African Savanna",
        book_description: "Facing the Lion: Growing Up Maasai on the African Savanna gives kids a firsthand look at growing up in Kenya as a member of a tribe of nomads whose livelihood centers on the raising and grazing of cattle. Readers share Lekuton's first encounter with a lion, the epitome of bravery in the warrior tradition. They follow his mischievous antics as a young Maasai cattle herder, coming-of-age initiation, boarding school escapades, soccer success, and journey to America for college. ",
        book_url: "https://cdn.shopify.com/s/files/1/0538/9349/7023/files/Facing_the_Lion-_Growing_Up_Maasai_on_the_African_Savanna_240x240.jpg?v=1631626265",
        print_length: "816 pages",
        language: "English",
        author_name: "Joseph Lemasolai Lekulon",
        price: "20000",
    },
    {
        id: 15,
        book_name: "My rows and piles of coins",
        book_description: "A Tanzanian boy saves his coins to buy a bicycle so that he can help his parents carry goods to market, but then he discovers that in spite of all he has saved, he still does not have enough money.",
        book_url: "https://m.media-amazon.com/images/I/91JehNGQcEL._SY425_.jpg",
        print_length: "32 pages",
        language: "English",
        author_name: "Tololwa M. Nollel, E.B. Lewis and Earl B. Lweis",
        price: "12000",
    },
    {
        id: 16,
        book_name: "Beatrice's Goat",
        book_description: "Based on a true story, this heartwarming picture book shows how one gift changed the fate of a poor Ugandan family—especially the young girl who wanted to go to school. More than anything, Beatrice longs to be a schoolgirl. But in her small African village, only children who can afford uniforms and books can go to school. Beatrice knows that with six children to care for, her family is much too poor. But then Beatrice receives a wonderful gift from some people far away—a goat! Fat and sleek as a ripe mango, Mugisa (“luck”) gives milk that Beatrice can sell. With Mugisa’s help, Beatrice’s dream may come true after all! Heifer Project International is a charitable organization that donates livestock to poor communities around the world, giving other families like Beatrice’s a chance to change their lives.",
        book_url: "https://m.media-amazon.com/images/I/61R6AGhvVkL._SY425_.jpg",
        print_length: "40 pages",
        language: "English",
        author_name: "Page McBrier",
        price: "15000",
    }
]